### ISSUE TITLE
NaN result from ArrayUtils.scale function if min or max is zero and just min or max is specified

### ISSUE THREAD

**Issue by jobo322** [mljs/array-utils#8] opened 2017-07-09 02:40 UTC

**Comment by targos** [comment] 2017-07-09 06:52
can you try with the new package: https://github.com/mljs/array/tree/master/packages/array-rescale ?

**Comment by maasencioh** [comment] 2017-07-10 07:28
I was reading the docs and the behavior indeed seems different, because with the test case of #9 in the new package will throw an error because the default value for max is 1 and `RangeError: min option must be smaller than max option`.

```js
var arrayRescale = require("ml-array-rescale")

var first = [0, 1, 2, 3];
arrayRescale(first, {min: 1, output: first});
```

Having this in mind I think that we should discuss what should be the expected behavior and use it in `ml-array-rescale`.

**Comment by targos** [comment] 2017-07-10 07:37
The usual way to rescale data in ML is between 0 and 1. I don't think it makes sense to default to the data's boundaries, but if you think otherwise, please explain your position.

**Comment by maasencioh** [comment] 2017-07-18 08:17
this is closed in https://github.com/mljs/array/commit/6f0ebe365fc0c1ba10d5c9fff024f5392f710815 and c83387198c01c5ee7e3293c8bb94bb68d3140744

**Closed by maasencioh** 2017-07-18 08:17 UTC
